name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: ng build --configuration production --base-href "https://diegodrf.github.io/smart-list-app/"

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/smart-list-app
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
